# Generated by Django 4.1.5 on 2023-03-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='product'),
        ),
    ]
