# Generated by Django 4.1.5 on 2023-03-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_product_pic2_product_pic3_product_pic4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic4',
        ),
    ]
