# Generated by Django 4.1.5 on 2023-03-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_remove_product_pic2_remove_product_pic3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='pic6',
            field=models.ImageField(blank=True, default='', null=True, upload_to='product'),
        ),
    ]
