# Generated by Django 4.1.5 on 2023-03-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_product_pic2_product_pic3_product_pic4_product_pic5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic6',
        ),
    ]
