# Generated by Django 4.1.5 on 2023-04-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_remove_product_pic2_remove_product_pic3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='otp',
            field=models.IntegerField(default=323232323232),
        ),
    ]
