# Generated by Django 4.1.5 on 2023-04-15 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_checkoutproducts_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='orderStatus',
            field=models.IntegerField(choices=[(0, 'Order placed'), (1, 'Not Packed'), (2, 'Packed'), (3, 'Ready to Dispatch'), (4, 'Dispatched'), (5, 'Out for Delivery'), (6, 'Delivered'), (7, 'Cancelled')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='baseprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='finalprice',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.product')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
            ],
        ),
    ]
