# Generated by Django 4.1.5 on 2023-04-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_checkout_orderstatus_alter_product_baseprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='otp',
            field=models.IntegerField(default=8898898),
        ),
    ]
